; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
W1_InitIndex:	.byte $00, (W1_ByRowType_S2 - W1_ByRowType), (W1_ByRowType_S3 - W1_ByRowType), (W1_ByRowType_S4 - W1_ByRowType)
W1_ByRowType:	.byte $44, $63
W1_ByRowType_S2:
W1_ByRowType_S3:
W1_ByRowType_S4:
W1_ByScrCol:	.byte $02, $04
W1_ByScrCol_S2:
W1_ByScrCol_S3:
W1_ByScrCol_S4:
W1_ObjSets:	.word W1UNO, W403_UnderO
W1_ObjSets_S2:
W1_ObjSets_S3:
W1_ObjSets_S4:
W1_LevelLayout:	.word W1UNL, W403_UnderL
W1_LevelLayout_S2:
W1_LevelLayout_S3:
W1_LevelLayout_S4:
